// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/ask-amanai.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/ai.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
var AMANAI_SYSTEM_PROMPT = `You are Amanai, a fully capable general-purpose AI assistant with expert-level knowledge across every domain \u2014 science, medicine, engineering, mathematics, code, law, finance, business, history, languages, arts, agriculture and everyday help. There is no topic restriction. Be factually accurate, direct and complete \u2014 never stop mid-sentence, no greetings or filler.
Match depth to the question and use the natural best format for the field (headings, bullets, tables, code blocks, LaTeX).
For plant, crop, pest, soil, disease or Indian agriculture questions only, use this compact block:
**Identity:** ... | **Health:** ... | **Diagnosis:** ...
**Action:** treatment, dosage, frequency | **Prevention:** ... | **Utility:** medicinal value or "None"
Prefer IPM -> organic (neem, Trichoderma, Panchagavya, Jeevamrutha) -> chemical as a last resort with safe dosage. Reference Indian schemes (PM-KISAN, PMFBY, MSP, nearest KVK) when relevant. Never force that format on non-agricultural questions.
Decline only genuinely illegal or seriously harmful requests; for medical, legal or financial specifics give the substantive answer plus a brief note to consult a professional.`;
async function askAmanai(userPrompt, opts = {}) {
  const apiKey = runtimeEnv("LOVABLE_API_KEY");
  if (!apiKey) throw new Error("LOVABLE_API_KEY is not configured");
  const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      model: opts.deep ? "google/gemini-3.1-pro-preview" : "google/gemini-3.8-flash",
      messages: [
        { role: "system", content: `${AMANAI_SYSTEM_PROMPT}${opts.systemExtra ? `
${opts.systemExtra}` : ""}` },
        { role: "user", content: userPrompt.slice(0, 4e3) }
      ],
      max_tokens: opts.deep ? 3e3 : 1500,
      temperature: opts.deep ? 0.3 : 0.7
    })
  });
  if (!response.ok) {
    if (response.status === 429) throw new Error("Rate limited by the AI gateway. Please retry shortly.");
    if (response.status === 402) throw new Error("AI usage limit reached for this workspace.");
    throw new Error(`AI gateway error (${response.status})`);
  }
  const data = await response.json();
  const text = data?.choices?.[0]?.message?.content;
  if (typeof text !== "string" || !text.trim()) throw new Error("The AI returned an empty response.");
  return text;
}

// src/lib/mcp/tools/ask-amanai.ts
var ask_amanai_default = defineTool({
  name: "ask_amanai",
  title: "Ask Amanai",
  description: "Ask Amanai, an expert general-purpose AI assistant, any question in any domain (science, code, medicine, business, agriculture, general knowledge) and get an accurate expert answer.",
  inputSchema: {
    question: z.string().trim().min(1).describe("The question to ask Amanai."),
    deep_reasoning: z.boolean().optional().describe("Set true for complex analysis that needs the slower, deeper reasoning model."),
    language: z.enum(["en", "hi", "od"]).optional().describe("Answer language: en (English), hi (Hindi), od (Odia). Defaults to English.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ question, deep_reasoning, language }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated.");
    const langExtra = language === "hi" ? "Respond entirely in Hindi (Devanagari); keep technical terms in English." : language === "od" ? "Respond entirely in Odia (\u0B13\u0B21\u0B3C\u0B3F\u0B06); keep technical terms in English." : void 0;
    try {
      const answer = await askAmanai(question, { deep: deep_reasoning === true, systemExtra: langExtra });
      return { content: [{ type: "text", text: answer }] };
    } catch (error) {
      throw new ToolError(error instanceof Error ? error.message : "Amanai could not answer that.");
    }
  }
});

// src/lib/mcp/tools/diagnose-crop.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var diagnose_crop_default = defineTool2({
  name: "diagnose_crop",
  title: "Diagnose crop",
  description: "Get a structured BloomSense diagnosis (identity, health, diagnosis, action, prevention, utility) for a crop from described symptoms.",
  inputSchema: {
    crop: z2.string().trim().min(1).describe("Crop or plant name, e.g. 'tomato', 'paddy'."),
    symptoms: z2.string().trim().min(1).describe("Observed symptoms, as detailed as possible."),
    location: z2.string().trim().optional().describe("Region or district, for climate-aware advice."),
    growth_stage: z2.string().trim().optional().describe("Crop growth stage, e.g. 'flowering', 'seedling'.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ crop, symptoms, location, growth_stage }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated.");
    const prompt = [
      `Crop: ${crop}`,
      `Symptoms: ${symptoms}`,
      location ? `Location: ${location}` : null,
      growth_stage ? `Growth stage: ${growth_stage}` : null,
      "Give the compact BloomSense diagnostic block, then two short lines of practical field notes."
    ].filter(Boolean).join("\n");
    try {
      const answer = await askAmanai(prompt, { deep: true });
      return { content: [{ type: "text", text: answer }] };
    } catch (error) {
      throw new ToolError2(error instanceof Error ? error.message : "Diagnosis failed.");
    }
  }
});

// src/lib/mcp/tools/search-disease-library.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";

// src/data/diseases.ts
var diseases = [
  {
    name: "Late Blight",
    hindiName: "\u091D\u0941\u0932\u0938\u093E \u0930\u094B\u0917",
    crops: ["Tomato", "Potato"],
    symptoms: "Dark water-soaked lesions on leaves, white fungal growth underneath",
    cause: "Phytophthora infestans (fungus-like oomycete)",
    treatment: "Mancozeb (Dithane M-45) 2.5g/L or Metalaxyl + Mancozeb (Ridomil Gold) 2g/L",
    prevention: "Avoid overhead irrigation, ensure air circulation, use resistant varieties",
    severity: "high",
    emoji: "\u{1F345}"
  },
  {
    name: "Powdery Mildew",
    hindiName: "\u091A\u0942\u0930\u094D\u0923\u093F\u0932 \u0906\u0938\u093F\u0924\u093E",
    crops: ["Cucurbits", "Peas", "Grapes"],
    symptoms: "White powdery coating on leaf surfaces, curling and yellowing",
    cause: "Erysiphe spp. / Podosphaera spp. (fungus)",
    treatment: "Sulphur WP 3g/L or Karathane (Dinocap) 1ml/L. Organic: Neem oil 5ml/L",
    prevention: "Proper spacing, avoid excess nitrogen, grow resistant varieties",
    severity: "medium",
    emoji: "\u{1F952}"
  },
  {
    name: "Bacterial Leaf Blight",
    hindiName: "\u091C\u0940\u0935\u093E\u0923\u0941 \u091D\u0941\u0932\u0938\u093E",
    crops: ["Rice", "Cotton"],
    symptoms: "Water-soaked streaks along veins, turning yellow-white and drying",
    cause: "Xanthomonas oryzae pv. oryzae",
    treatment: "Streptocycline 1g + Copper oxychloride 25g per 10L. No effective chemical cure \u2014 manage early",
    prevention: "Use certified seed, balanced fertilization, avoid excess nitrogen",
    severity: "high",
    emoji: "\u{1F33E}"
  },
  {
    name: "Fusarium Wilt",
    hindiName: "\u0909\u0915\u0920\u093E \u0930\u094B\u0917",
    crops: ["Tomato", "Banana", "Chickpea"],
    symptoms: "Yellowing of lower leaves, wilting despite adequate water, brown vascular discoloration",
    cause: "Fusarium oxysporum (soil-borne fungus)",
    treatment: "Trichoderma viride 5g/kg seed treatment. Carbendazim (Bavistin) 1g/L soil drench",
    prevention: "Crop rotation (3\u20134 years), solarize soil, use resistant rootstocks",
    severity: "high",
    emoji: "\u{1F34C}"
  },
  {
    name: "Aphid Infestation",
    hindiName: "\u092E\u093E\u0939\u0942 / \u091A\u0947\u0902\u092A\u093E",
    crops: ["Mustard", "Wheat", "Vegetables"],
    symptoms: "Curled leaves, sticky honeydew, sooty mold, stunted growth",
    cause: "Lipaphis erysimi / Aphis gossypii (sucking pest)",
    treatment: "Neem oil 5ml/L or Imidacloprid (Confidor) 0.3ml/L. Release ladybird beetles as biocontrol",
    prevention: "Yellow sticky traps, intercropping with coriander, avoid excess nitrogen",
    severity: "medium",
    emoji: "\u{1F41B}"
  },
  {
    name: "Downy Mildew",
    hindiName: "\u092E\u0943\u0926\u0941\u0930\u094B\u092E\u093F\u0932 \u0906\u0938\u093F\u0924\u093E",
    crops: ["Grapes", "Cucurbits", "Onion"],
    symptoms: "Yellow angular spots on upper leaf, purplish-grey fungal growth below",
    cause: "Peronospora spp. / Pseudoperonospora spp.",
    treatment: "Metalaxyl + Mancozeb (Ridomil Gold) 2g/L or Copper oxychloride 3g/L",
    prevention: "Avoid waterlogging, morning irrigation, prune for air flow",
    severity: "medium",
    emoji: "\u{1F347}"
  },
  {
    name: "Root Knot Nematode",
    hindiName: "\u091C\u0921\u093C \u0917\u093E\u0902\u0920 \u0938\u0942\u0924\u094D\u0930\u0915\u0943\u092E\u093F",
    crops: ["Tomato", "Brinjal", "Okra", "Carrot"],
    symptoms: "Stunting, wilting in heat, swollen galls/knots on roots",
    cause: "Meloidogyne incognita (nematode)",
    treatment: "Paecilomyces lilacinus or Carbofuran 1kg a.i./ha at transplanting. Neem cake 250kg/ha",
    prevention: "Marigold intercrop/rotation, solarization, resistant varieties",
    severity: "high",
    emoji: "\u{1F955}"
  },
  {
    name: "Leaf Curl Virus",
    hindiName: "\u092A\u0924\u094D\u0924\u0940 \u092E\u094B\u0921\u093C\u0915 \u0935\u093F\u0937\u093E\u0923\u0941",
    crops: ["Tomato", "Chilli", "Cotton"],
    symptoms: "Upward curling, puckering, reduced leaf size, stunted plants",
    cause: "Begomovirus transmitted by whitefly (Bemisia tabaci)",
    treatment: "No cure. Remove infected plants. Control whitefly: Imidacloprid 0.3ml/L or neem oil",
    prevention: "Use virus-free seedlings, silver mulch to repel whitefly, resistant hybrids",
    severity: "high",
    emoji: "\u{1F336}\uFE0F"
  },
  {
    name: "Early Blight",
    hindiName: "\u0905\u0917\u0947\u0924\u0940 \u091D\u0941\u0932\u0938\u093E",
    crops: ["Tomato", "Potato", "Brinjal"],
    symptoms: "Brown spots with concentric rings (target/bullseye pattern) on older lower leaves, yellow halo around spots, leaves drop from bottom upward",
    cause: "Alternaria solani (fungus), favoured by warm humid weather and alternating wet-dry spells",
    treatment: "Mancozeb 2.5g/L or Chlorothalonil 2g/L at 10-day intervals. Organic: Trichoderma + neem oil 5ml/L",
    prevention: "Mulch to stop soil splash, remove lower infected foliage, 3-year rotation, stake plants",
    severity: "high",
    emoji: "\u{1F3AF}"
  },
  {
    name: "Rice Blast",
    hindiName: "\u0930\u093F\u091A \u091D\u094B\u0902\u0915\u093E / \u092C\u094D\u0932\u093E\u0938\u094D\u091F",
    crops: ["Rice", "Finger Millet"],
    symptoms: "Diamond/spindle-shaped spots with grey centre and brown margin on leaves; blackened rotting node; neck of panicle breaks and grain fills poorly",
    cause: "Magnaporthe oryzae (Pyricularia oryzae), severe in cool nights with heavy dew and high nitrogen",
    treatment: "Tricyclazole 0.6g/L or Isoprothiolane 1.5ml/L at boot-leaf and heading stage. Seed treat with Carbendazim 2g/kg",
    prevention: "Split nitrogen doses, avoid dense planting, resistant varieties, drain field periodically",
    severity: "high",
    emoji: "\u{1F33E}"
  },
  {
    name: "Wheat Rust",
    hindiName: "\u0917\u0947\u0930\u0941\u0906 \u0930\u094B\u0917",
    crops: ["Wheat", "Barley", "Oats"],
    symptoms: "Orange-brown or yellow powdery pustules in stripes or scattered dots on leaves and stem; rusty powder rubs off on fingers and clothes",
    cause: "Puccinia species (stripe, leaf and stem rust), spreads on wind in cool moist weather",
    treatment: "Propiconazole 1ml/L or Tebuconazole 1ml/L, repeat after 15 days if pustules persist",
    prevention: "Sow rust-resistant varieties, timely sowing, destroy volunteer wheat plants",
    severity: "high",
    emoji: "\u{1F7E0}"
  },
  {
    name: "Mosaic Virus",
    hindiName: "\u092E\u094B\u091C\u0947\u0915 \u0935\u093F\u0937\u093E\u0923\u0941",
    crops: ["Tomato", "Okra", "Cucurbits", "Papaya", "Tobacco"],
    symptoms: "Mottled light-and-dark green patchwork on leaves, blistered puckered surface, narrow strap-like distorted new leaves, stunted plant, poor fruit set",
    cause: "Tobacco/Cucumber mosaic virus and Yellow Vein Mosaic, spread by aphids, whitefly and handling",
    treatment: "No chemical cure. Uproot and burn infected plants. Control vectors: Imidacloprid 0.3ml/L or neem oil 5ml/L",
    prevention: "Virus-free seed, wash hands and tools, no tobacco use near crop, barrier crop of maize",
    severity: "high",
    emoji: "\u{1F9E9}"
  },
  {
    name: "Anthracnose",
    hindiName: "\u0936\u094D\u092F\u093E\u092E\u0935\u0930\u094D\u0923 / \u090F\u0928\u094D\u0925\u094D\u0930\u0947\u0915\u094D\u0928\u094B\u091C",
    crops: ["Chilli", "Mango", "Beans", "Banana"],
    symptoms: "Sunken circular dark spots on fruit with pink spore masses in the centre, fruit rots and dries; twig dieback in mango",
    cause: "Colletotrichum species, spreads in rain splash at fruit maturity",
    treatment: "Carbendazim 1g/L or Mancozeb 2.5g/L sprays at flowering and fruit set",
    prevention: "Harvest dry fruit, remove mummified fruit, avoid overhead irrigation, proper spacing",
    severity: "medium",
    emoji: "\u{1F336}\uFE0F"
  },
  {
    name: "Damping Off",
    hindiName: "\u0906\u0930\u094D\u0926\u094D\u0930 \u0917\u0932\u0928",
    crops: ["Nursery seedlings", "Tomato", "Chilli", "Brinjal", "Cabbage"],
    symptoms: "Seedlings collapse and topple at soil line, stem base water-soaked and pinched thin, patches of dead seedlings in nursery bed",
    cause: "Pythium and Rhizoctonia in overwatered, poorly drained, crowded nursery beds",
    treatment: "Drench with Copper oxychloride 3g/L or Metalaxyl 2g/L; reduce watering immediately",
    prevention: "Raised nursery beds, soil solarisation, Trichoderma 10g/kg soil, thin sowing",
    severity: "high",
    emoji: "\u{1F331}"
  },
  {
    name: "Stem Borer",
    hindiName: "\u0924\u0928\u093E \u091B\u0947\u0926\u0915",
    crops: ["Rice", "Maize", "Sugarcane", "Brinjal"],
    symptoms: "Dead heart in young plants \u2014 central shoot dries and pulls out easily; white empty panicles (white ear) later; bore holes with frass on stem",
    cause: "Scirpophaga incertulas / Chilo species (moth larvae tunnelling inside the stem)",
    treatment: "Cartap hydrochloride 4G 18kg/ha or Chlorantraniliprole 0.3ml/L. Release Trichogramma cards",
    prevention: "Clip seedling tips before transplanting, pheromone traps, destroy stubble after harvest",
    severity: "high",
    emoji: "\u{1F41B}"
  },
  {
    name: "Fruit & Shoot Borer",
    hindiName: "\u092B\u0932 \u090F\u0935\u0902 \u092A\u094D\u0930\u0930\u094B\u0939 \u091B\u0947\u0926\u0915",
    crops: ["Brinjal", "Okra", "Tomato"],
    symptoms: "Young shoots wilt and droop, bore hole plugged with excreta on fruit, tunnels and larva inside the fruit when cut open",
    cause: "Leucinodes orbonalis / Earias species",
    treatment: "Emamectin benzoate 0.4g/L or Spinosad 0.3ml/L. Handpick and destroy bored fruit",
    prevention: "Pheromone traps 5/acre, remove wilted shoots weekly, resistant long-fruited varieties",
    severity: "medium",
    emoji: "\u{1F346}"
  },
  {
    name: "Whitefly",
    hindiName: "\u0938\u092B\u0947\u0926 \u092E\u0915\u094D\u0916\u0940",
    crops: ["Cotton", "Tomato", "Chilli", "Brinjal", "Pulses"],
    symptoms: "Tiny white insects fly up in a cloud when plant is shaken, undersides of leaves sticky, black sooty mould, leaves yellow and curl, virus spreads fast",
    cause: "Bemisia tabaci (sucking pest and virus vector)",
    treatment: "Diafenthiuron 1g/L or Spiromesifen 1ml/L; organic: neem oil 5ml/L + sticky yellow traps",
    prevention: "Yellow sticky traps 10/acre, silver reflective mulch, avoid excess nitrogen, border maize rows",
    severity: "high",
    emoji: "\u{1F99F}"
  },
  {
    name: "Thrips",
    hindiName: "\u0925\u094D\u0930\u093F\u092A\u094D\u0938",
    crops: ["Chilli", "Onion", "Cotton", "Grapes"],
    symptoms: "Leaves curl upward like a boat (leaf curl), silvery streaks and scratch marks, buds drop, flowers dry and fall",
    cause: "Scirtothrips dorsalis / Thrips tabaci (rasping-sucking pest, severe in dry heat)",
    treatment: "Fipronil 1.5ml/L or Spinosad 0.3ml/L; organic: neem oil 5ml/L + blue sticky traps",
    prevention: "Blue sticky traps, sprinkler irrigation to raise humidity, remove weed hosts",
    severity: "medium",
    emoji: "\u{1F336}\uFE0F"
  },
  {
    name: "Bacterial Wilt",
    hindiName: "\u091C\u0940\u0935\u093E\u0923\u0941 \u0909\u0915\u0920\u093E",
    crops: ["Tomato", "Brinjal", "Potato", "Chilli", "Ginger"],
    symptoms: "Sudden wilting of a green healthy-looking plant without yellowing; cut stem placed in water oozes milky white bacterial threads",
    cause: "Ralstonia solanacearum (soil and water-borne bacterium)",
    treatment: "No cure. Uproot and burn affected plants, drench pit with bleaching powder 15kg/ha or Copper oxychloride 3g/L",
    prevention: "Rotate with cereals for 3 years, grafted resistant rootstock, raised beds and good drainage",
    severity: "high",
    emoji: "\u{1F954}"
  },
  {
    name: "Citrus Greening (HLB)",
    hindiName: "\u0928\u0940\u0902\u092C\u0942 \u0939\u0930\u093F\u0924\u0924\u093E \u0930\u094B\u0917",
    crops: ["Citrus", "Orange", "Lemon", "Kinnow"],
    symptoms: "Blotchy asymmetric yellow mottling across the leaf midrib, twig dieback, small lopsided bitter fruit that drops early",
    cause: "Candidatus Liberibacter, spread by citrus psyllid (Diaphorina citri)",
    treatment: "No cure. Remove infected trees. Control psyllid with Imidacloprid 0.3ml/L; tetracycline trunk injection gives temporary relief",
    prevention: "Certified disease-free saplings, monitor and spray psyllid on new flush, remove curry leaf hosts",
    severity: "high",
    emoji: "\u{1F34A}"
  },
  {
    name: "Nitrogen Deficiency",
    hindiName: "\u0928\u093E\u0907\u091F\u094D\u0930\u094B\u091C\u0928 \u0915\u0940 \u0915\u092E\u0940",
    crops: ["All crops", "Rice", "Wheat", "Maize", "Vegetables"],
    symptoms: "Uniform pale yellow older lower leaves with yellowing starting from the leaf tip along the midrib, thin stems, slow stunted growth, no spots or lesions",
    cause: "Insufficient nitrogen, leaching after heavy rain, or unfinished organic matter tying up nitrogen",
    treatment: "Top-dress Urea 40-50kg/ha or spray 2% urea solution for a quick recovery within a week",
    prevention: "Split nitrogen application, green manure, FYM 10t/ha, soil test before the season",
    severity: "medium",
    emoji: "\u{1F49B}"
  },
  {
    name: "Zinc Deficiency",
    hindiName: "\u091C\u093F\u0902\u0915 \u0915\u0940 \u0915\u092E\u0940 (\u0916\u0948\u0930\u093E \u0930\u094B\u0917)",
    crops: ["Rice", "Maize", "Wheat", "Citrus"],
    symptoms: "Rusty brown patches on middle leaves of young rice (khaira), white or pale bands between veins, shortened internodes, small bunched leaves at the tip",
    cause: "Low available zinc, common in alkaline, calcareous and continuously flooded soils",
    treatment: "Spray Zinc sulphate 0.5% (5g/L) with lime twice at 10-day gap; soil apply 25kg ZnSO4/ha",
    prevention: "Apply zinc every 2-3 seasons, avoid continuous flooding, add organic manure",
    severity: "medium",
    emoji: "\u{1F9EA}"
  },
  {
    name: "Iron Deficiency",
    hindiName: "\u0932\u094C\u0939 \u0924\u0924\u094D\u0935 \u0915\u0940 \u0915\u092E\u0940",
    crops: ["Citrus", "Groundnut", "Soybean", "Vegetables"],
    symptoms: "Youngest top leaves turn pale yellow or white while veins stay bright green (interveinal chlorosis); older leaves remain normal",
    cause: "Iron locked up in high-pH calcareous soil or waterlogged roots, not a true shortage",
    treatment: "Spray Ferrous sulphate 0.5% (5g/L) + citric acid 1g/L, two to three sprays at weekly gaps",
    prevention: "Improve drainage, add organic matter, avoid over-liming, use chelated iron in alkaline soil",
    severity: "low",
    emoji: "\u{1F34B}"
  },
  {
    name: "Fall Armyworm",
    hindiName: "\u092B\u0949\u0932 \u0906\u0930\u094D\u092E\u0940\u0935\u0930\u094D\u092E",
    crops: ["Maize", "Sorghum", "Sugarcane", "Millets"],
    symptoms: "Ragged window-pane holes and shot holes in whorl leaves, moist sawdust-like frass in the funnel, large larva with inverted Y on head",
    cause: "Spodoptera frugiperda (invasive caterpillar)",
    treatment: "Emamectin benzoate 0.4g/L or Spinetoram 0.5ml/L poured into the whorl in the evening. Sand + lime in whorl for small larvae",
    prevention: "Early uniform sowing, pheromone traps 5/acre, intercrop with pulses, encourage birds",
    severity: "high",
    emoji: "\u{1F33D}"
  },
  {
    name: "Sheath Blight",
    hindiName: "\u0936\u0940\u0925 \u092C\u094D\u0932\u093E\u0907\u091F",
    crops: ["Rice"],
    symptoms: "Oval greenish-grey water-soaked patches on the leaf sheath near the water line, later becoming straw-coloured with brown borders; sheath rots and tillers lodge",
    cause: "Rhizoctonia solani, worst in dense crops with heavy nitrogen and high humidity",
    treatment: "Validamycin 2ml/L or Hexaconazole 2ml/L directed at the base of the plant",
    prevention: "Wider spacing, balanced nitrogen, remove weeds and stubble, alternate wet-dry irrigation",
    severity: "medium",
    emoji: "\u{1F33E}"
  },
  {
    name: "Red Rot of Sugarcane",
    hindiName: "\u0932\u093E\u0932 \u0938\u0921\u093C\u0928 \u0930\u094B\u0917",
    crops: ["Sugarcane"],
    symptoms: "Third and fourth leaves yellow and dry, split cane shows red internal tissue with crosswise white patches and a sour alcoholic smell",
    cause: "Colletotrichum falcatum, spread through infected setts and irrigation water",
    treatment: "No cure for a standing infected clump. Uproot and burn, drench the pit with Carbendazim 1g/L",
    prevention: "Disease-free setts, hot water treatment of setts at 52\xB0C, resistant varieties, crop rotation",
    severity: "high",
    emoji: "\u{1F38B}"
  }
];

// src/lib/mcp/tools/search-disease-library.ts
var search_disease_library_default = defineTool3({
  name: "search_disease_library",
  title: "Search disease library",
  description: "Search the BloomSense plant disease library by disease name, Hindi name or crop, and return symptoms, cause, treatment and prevention.",
  inputSchema: {
    query: z3.string().trim().optional().describe("Disease name, Hindi name or crop to search for. Omit to list the whole library.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated.");
    const q = (query ?? "").toLowerCase();
    const results = diseases.filter(
      (d) => !q || d.name.toLowerCase().includes(q) || d.hindiName.includes(query ?? "") || d.crops.some((c) => c.toLowerCase().includes(q))
    );
    if (results.length === 0) {
      return { content: [{ type: "text", text: `No disease in the library matches "${query}".` }] };
    }
    const text = results.map(
      (d) => `## ${d.name} (${d.hindiName})
Severity: ${d.severity}
Crops: ${d.crops.join(", ")}
Symptoms: ${d.symptoms}
Cause: ${d.cause}
Treatment: ${d.treatment}
Prevention: ${d.prevention}`
    ).join("\n\n");
    return { content: [{ type: "text", text }], structuredContent: { count: results.length, diseases: results } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kkiqgaxtfeswzfmqixfm";
var mcp_default = defineMcp({
  name: "amania-bloomsense",
  title: "Amania bloomsense",
  version: "0.1.0",
  instructions: "Tools for Amanai, the BloomSense master botanist. Use `ask_amanai` for any agronomy or general question, `diagnose_crop` for a structured crop diagnosis, `search_disease_library` to look up Indian crop diseases with treatments.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [ask_amanai_default, diagnose_crop_default, search_disease_library_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
