// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/ask-amanai.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/ai.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
var AMANAI_SYSTEM_PROMPT = `You are Amanai, the BloomSense master botanist and a world-class general-purpose assistant. Be factually accurate, concise and complete \u2014 never stop mid-sentence.
For plant, crop, pest, soil, disease or Indian agriculture questions, answer with this compact block:
**Identity:** ... | **Health:** ... | **Diagnosis:** ...
**Action:** treatment, dosage, frequency | **Prevention:** ... | **Utility:** medicinal value or "None"
Prefer IPM -> organic (neem, Trichoderma, Panchagavya, Jeevamrutha) -> chemical as a last resort with safe dosage. Reference Indian schemes (PM-KISAN, PMFBY, MSP, nearest KVK) when relevant. Do not force that format on non-agricultural questions.`;
async function askAmanai(userPrompt, opts = {}) {
  const apiKey = runtimeEnv("LOVABLE_API_KEY");
  if (!apiKey) throw new Error("LOVABLE_API_KEY is not configured");
  const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      model: opts.deep ? "google/gemini-3.1-pro-preview" : "google/gemini-3.5-flash",
      messages: [
        { role: "system", content: `${AMANAI_SYSTEM_PROMPT}${opts.systemExtra ? `
${opts.systemExtra}` : ""}` },
        { role: "user", content: userPrompt.slice(0, 4e3) }
      ],
      max_tokens: opts.deep ? 3e3 : 1500,
      temperature: opts.deep ? 0.3 : 0.7
    })
  });
  if (!response.ok) {
    if (response.status === 429) throw new Error("Rate limited by the AI gateway. Please retry shortly.");
    if (response.status === 402) throw new Error("AI usage limit reached for this workspace.");
    throw new Error(`AI gateway error (${response.status})`);
  }
  const data = await response.json();
  const text = data?.choices?.[0]?.message?.content;
  if (typeof text !== "string" || !text.trim()) throw new Error("The AI returned an empty response.");
  return text;
}

// src/lib/mcp/tools/ask-amanai.ts
var ask_amanai_default = defineTool({
  name: "ask_amanai",
  title: "Ask Amanai",
  description: "Ask Amanai, the BloomSense master botanist, any agronomy, crop, plant-health or general-knowledge question and get an expert answer.",
  inputSchema: {
    question: z.string().trim().min(1).describe("The question to ask Amanai."),
    deep_reasoning: z.boolean().optional().describe("Set true for complex analysis that needs the slower, deeper reasoning model."),
    language: z.enum(["en", "hi", "od"]).optional().describe("Answer language: en (English), hi (Hindi), od (Odia). Defaults to English.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ question, deep_reasoning, language }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated.");
    const langExtra = language === "hi" ? "Respond entirely in Hindi (Devanagari); keep technical terms in English." : language === "od" ? "Respond entirely in Odia (\u0B13\u0B21\u0B3C\u0B3F\u0B06); keep technical terms in English." : void 0;
    try {
      const answer = await askAmanai(question, { deep: deep_reasoning === true, systemExtra: langExtra });
      return { content: [{ type: "text", text: answer }] };
    } catch (error) {
      throw new ToolError(error instanceof Error ? error.message : "Amanai could not answer that.");
    }
  }
});

// src/lib/mcp/tools/diagnose-crop.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var diagnose_crop_default = defineTool2({
  name: "diagnose_crop",
  title: "Diagnose crop",
  description: "Get a structured BloomSense diagnosis (identity, health, diagnosis, action, prevention, utility) for a crop from described symptoms.",
  inputSchema: {
    crop: z2.string().trim().min(1).describe("Crop or plant name, e.g. 'tomato', 'paddy'."),
    symptoms: z2.string().trim().min(1).describe("Observed symptoms, as detailed as possible."),
    location: z2.string().trim().optional().describe("Region or district, for climate-aware advice."),
    growth_stage: z2.string().trim().optional().describe("Crop growth stage, e.g. 'flowering', 'seedling'.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ crop, symptoms, location, growth_stage }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated.");
    const prompt = [
      `Crop: ${crop}`,
      `Symptoms: ${symptoms}`,
      location ? `Location: ${location}` : null,
      growth_stage ? `Growth stage: ${growth_stage}` : null,
      "Give the compact BloomSense diagnostic block, then two short lines of practical field notes."
    ].filter(Boolean).join("\n");
    try {
      const answer = await askAmanai(prompt, { deep: true });
      return { content: [{ type: "text", text: answer }] };
    } catch (error) {
      throw new ToolError2(error instanceof Error ? error.message : "Diagnosis failed.");
    }
  }
});

// src/lib/mcp/tools/search-disease-library.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";

// src/data/diseases.ts
var diseases = [
  {
    name: "Late Blight",
    hindiName: "\u091D\u0941\u0932\u0938\u093E \u0930\u094B\u0917",
    crops: ["Tomato", "Potato"],
    symptoms: "Dark water-soaked lesions on leaves, white fungal growth underneath",
    cause: "Phytophthora infestans (fungus-like oomycete)",
    treatment: "Mancozeb (Dithane M-45) 2.5g/L or Metalaxyl + Mancozeb (Ridomil Gold) 2g/L",
    prevention: "Avoid overhead irrigation, ensure air circulation, use resistant varieties",
    severity: "high",
    emoji: "\u{1F345}"
  },
  {
    name: "Powdery Mildew",
    hindiName: "\u091A\u0942\u0930\u094D\u0923\u093F\u0932 \u0906\u0938\u093F\u0924\u093E",
    crops: ["Cucurbits", "Peas", "Grapes"],
    symptoms: "White powdery coating on leaf surfaces, curling and yellowing",
    cause: "Erysiphe spp. / Podosphaera spp. (fungus)",
    treatment: "Sulphur WP 3g/L or Karathane (Dinocap) 1ml/L. Organic: Neem oil 5ml/L",
    prevention: "Proper spacing, avoid excess nitrogen, grow resistant varieties",
    severity: "medium",
    emoji: "\u{1F952}"
  },
  {
    name: "Bacterial Leaf Blight",
    hindiName: "\u091C\u0940\u0935\u093E\u0923\u0941 \u091D\u0941\u0932\u0938\u093E",
    crops: ["Rice", "Cotton"],
    symptoms: "Water-soaked streaks along veins, turning yellow-white and drying",
    cause: "Xanthomonas oryzae pv. oryzae",
    treatment: "Streptocycline 1g + Copper oxychloride 25g per 10L. No effective chemical cure \u2014 manage early",
    prevention: "Use certified seed, balanced fertilization, avoid excess nitrogen",
    severity: "high",
    emoji: "\u{1F33E}"
  },
  {
    name: "Fusarium Wilt",
    hindiName: "\u0909\u0915\u0920\u093E \u0930\u094B\u0917",
    crops: ["Tomato", "Banana", "Chickpea"],
    symptoms: "Yellowing of lower leaves, wilting despite adequate water, brown vascular discoloration",
    cause: "Fusarium oxysporum (soil-borne fungus)",
    treatment: "Trichoderma viride 5g/kg seed treatment. Carbendazim (Bavistin) 1g/L soil drench",
    prevention: "Crop rotation (3\u20134 years), solarize soil, use resistant rootstocks",
    severity: "high",
    emoji: "\u{1F34C}"
  },
  {
    name: "Aphid Infestation",
    hindiName: "\u092E\u093E\u0939\u0942 / \u091A\u0947\u0902\u092A\u093E",
    crops: ["Mustard", "Wheat", "Vegetables"],
    symptoms: "Curled leaves, sticky honeydew, sooty mold, stunted growth",
    cause: "Lipaphis erysimi / Aphis gossypii (sucking pest)",
    treatment: "Neem oil 5ml/L or Imidacloprid (Confidor) 0.3ml/L. Release ladybird beetles as biocontrol",
    prevention: "Yellow sticky traps, intercropping with coriander, avoid excess nitrogen",
    severity: "medium",
    emoji: "\u{1F41B}"
  },
  {
    name: "Downy Mildew",
    hindiName: "\u092E\u0943\u0926\u0941\u0930\u094B\u092E\u093F\u0932 \u0906\u0938\u093F\u0924\u093E",
    crops: ["Grapes", "Cucurbits", "Onion"],
    symptoms: "Yellow angular spots on upper leaf, purplish-grey fungal growth below",
    cause: "Peronospora spp. / Pseudoperonospora spp.",
    treatment: "Metalaxyl + Mancozeb (Ridomil Gold) 2g/L or Copper oxychloride 3g/L",
    prevention: "Avoid waterlogging, morning irrigation, prune for air flow",
    severity: "medium",
    emoji: "\u{1F347}"
  },
  {
    name: "Root Knot Nematode",
    hindiName: "\u091C\u0921\u093C \u0917\u093E\u0902\u0920 \u0938\u0942\u0924\u094D\u0930\u0915\u0943\u092E\u093F",
    crops: ["Tomato", "Brinjal", "Okra", "Carrot"],
    symptoms: "Stunting, wilting in heat, swollen galls/knots on roots",
    cause: "Meloidogyne incognita (nematode)",
    treatment: "Paecilomyces lilacinus or Carbofuran 1kg a.i./ha at transplanting. Neem cake 250kg/ha",
    prevention: "Marigold intercrop/rotation, solarization, resistant varieties",
    severity: "high",
    emoji: "\u{1F955}"
  },
  {
    name: "Leaf Curl Virus",
    hindiName: "\u092A\u0924\u094D\u0924\u0940 \u092E\u094B\u0921\u093C\u0915 \u0935\u093F\u0937\u093E\u0923\u0941",
    crops: ["Tomato", "Chilli", "Cotton"],
    symptoms: "Upward curling, puckering, reduced leaf size, stunted plants",
    cause: "Begomovirus transmitted by whitefly (Bemisia tabaci)",
    treatment: "No cure. Remove infected plants. Control whitefly: Imidacloprid 0.3ml/L or neem oil",
    prevention: "Use virus-free seedlings, silver mulch to repel whitefly, resistant hybrids",
    severity: "high",
    emoji: "\u{1F336}\uFE0F"
  }
];

// src/lib/mcp/tools/search-disease-library.ts
var search_disease_library_default = defineTool3({
  name: "search_disease_library",
  title: "Search disease library",
  description: "Search the BloomSense plant disease library by disease name, Hindi name or crop, and return symptoms, cause, treatment and prevention.",
  inputSchema: {
    query: z3.string().trim().optional().describe("Disease name, Hindi name or crop to search for. Omit to list the whole library.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated.");
    const q = (query ?? "").toLowerCase();
    const results = diseases.filter(
      (d) => !q || d.name.toLowerCase().includes(q) || d.hindiName.includes(query ?? "") || d.crops.some((c) => c.toLowerCase().includes(q))
    );
    if (results.length === 0) {
      return { content: [{ type: "text", text: `No disease in the library matches "${query}".` }] };
    }
    const text = results.map(
      (d) => `## ${d.name} (${d.hindiName})
Severity: ${d.severity}
Crops: ${d.crops.join(", ")}
Symptoms: ${d.symptoms}
Cause: ${d.cause}
Treatment: ${d.treatment}
Prevention: ${d.prevention}`
    ).join("\n\n");
    return { content: [{ type: "text", text }], structuredContent: { count: results.length, diseases: results } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kkiqgaxtfeswzfmqixfm";
var mcp_default = defineMcp({
  name: "amania-bloomsense",
  title: "Amania bloomsense",
  version: "0.1.0",
  instructions: "Tools for Amanai, the BloomSense master botanist. Use `ask_amanai` for any agronomy or general question, `diagnose_crop` for a structured crop diagnosis, `search_disease_library` to look up Indian crop diseases with treatments.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [ask_amanai_default, diagnose_crop_default, search_disease_library_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
